"""
配置示例文件
复制此文件为 config.py 并修改配置
注意：不要将 config.py 提交到版本控制系统

也可以使用以下环境变量，它们的优先级高于本文件：
- PICIX_BOT_TOKEN
- PICIX_AUTHORIZATION（可选；Bot 自动续期后无需手动设置）
- PICIX_ALLOWED_USER_IDS（多个 ID 用英文逗号分隔）
- PICIX_NOTIFICATION_THRESHOLD
- PICIX_CHECK_INTERVAL
- PICIX_AUTO_UNLOCK_HOUR
- PICIX_AUTO_UNLOCK_MINUTE
- PICIX_AUTO_OPTIMIZE
- PICIX_AUTO_PURCHASE
- PICIX_TIMEZONE
- PICIX_MINIMUM_MONTHLY_SPEND
- PICIX_PACKAGE_GOOD_ID
- PICIX_PACKAGE_PRICE
- PICIX_PACKAGE_QUOTA
- PICIX_SPEND_CYCLE_DAYS
- PICIX_SPEND_TRIGGER_DAY
- PICIX_POINTS_RESERVE
- PICIX_MAX_AUTO_PURCHASES
- PICIX_MAX_AUTO_UNLOCKS
"""

# Bot Token 等秘密请写入 .env，不要写进 Python 文件。

# 用户权限配置
ALLOWED_USER_IDS = []  # 空列表时先用 /setuser 完成首次初始化
# 或者填入允许的用户ID列表，例如：
# ALLOWED_USER_IDS = [123456789, 987654321]

# 通知阈值
NOTIFICATION_THRESHOLD = 10  # 剩余次数低于此值时通知用户

# 检查间隔（秒）
CHECK_INTERVAL = 3600  # 每小时检查一次（3600秒）

# 每日自动解锁时间
AUTO_UNLOCK_HOUR = 9
AUTO_UNLOCK_MINUTE = 0

# 自动积分优化（AUTO_PURCHASE=True 会真实扣除积分购买资源包）
AUTO_OPTIMIZE = True
AUTO_PURCHASE = True
TIMEZONE = "Asia/Shanghai"
MINIMUM_MONTHLY_SPEND = 450
PACKAGE_GOOD_ID = "1"
PACKAGE_PRICE = 450
PACKAGE_QUOTA = 30
SPEND_CYCLE_DAYS = 30
SPEND_TRIGGER_DAY = 25
POINTS_RESERVE = 0
MAX_AUTO_PURCHASES = 2
MAX_AUTO_UNLOCKS = 50
